### ISSUE TITLE
Not working on electra jailbreak 11.1

### ISSUE THREAD

**Issue by Inc0n** [DGh0st/DVirtualHome#1]
Gestures are created fine, _createGestureRecognizersWithConfiguration is called, however, 
gesture actions are not called, such as singleTapUp, longTap, tapAndHold, etc.

Essentially, no response when tapping, holding or tapAndHolding Touch ID.

**Comment by DGh0st** [comment]
Yea this requires reachability to be turned on via `Settings > General > Accessibility > Reachability (Enable Switch)`.

**Comment by Inc0n** [comment]
Oops forgot to mention iPad user here
