### ISSUE TITLE
-[SBSystemGestureManager display] method not exist

### ISSUE THREAD

**Issue by Inc0n** [DGh0st/DVirtualHome#2]
On iOS 11.1 class "SBSystemGestureManager" does not have instance method "display":
therefore, in methods:
* createLongTapGestureRecognizerWithConfiguration
* createSingleTapGestureRecognizerWithConfiguration
* createTapAndHoldGestureRecognizerWithConfiguration

this code
`[_fbSystemGestureManager addGestureRecognizer:_longTapGestureRecognizer toDisplay:[_systemGestureManager display]];`
would cause error
>EXE_CRASH

**Comment by DGh0st** [comment]
I don't have an iOS 11 device to test this on, but the [the If on Line 168](https://github.com/DGh0st/DVirtualHome/blob/master/Tweak.xm#L168) and [else if on Line 170](https://github.com/DGh0st/DVirtualHome/blob/master/Tweak.xm#L170) need to be swapped. So it should be
```
if ([_fbSystemGestureManager respondsToSelector:@selector(addGestureRecognizer:toDisplayWithIdentity:)])
    [_fbSystemGestureManager addGestureRecognizer:_singleTapGestureRecognizer toDisplayWithIdentity:MSHookIvar<id>(_systemGestureManager, "_displayIdentity")];
else if ([_fbSystemGestureManager respondsToSelector:@selector(addGestureRecognizer:toDisplay:)])
    [_fbSystemGestureManager addGestureRecognizer:_singleTapGestureRecognizer toDisplay:[_systemGestureManager display]];
```

Same applies for the Line 190 and Line 210.

**Comment by Inc0n** [comment]
is this method removed from iOS 11
