### ISSUE TITLE
ios 15 crashes on home button single tap

### ISSUE THREAD

**Issue by antalm** [DGh0st/DVirtualHome#8]
App switcher works correctly but home button crashes the iPhone and it resprings into safe mode. As a workaround I can use the app switcher then click to the background to go to the home screen, but it would be nice if home button worked on iOS 15.7.2.

**Comment by DGh0st** [comment]
Please share the crashlog.

**Comment by antalm** [comment]
This is what I found in /var/mobile/Library/Logs/CrashReporter/SpringBoard.ips (renamed to .txt for github)

[SpringBoard.txt](https://github.com/DGh0st/DVirtualHome/files/10326093/SpringBoard.txt)

**Comment by DGh0st** [comment]
The simpler version of the simulate home button press method was removed in iOS 15. Using the non-simpler method starting [feacb38](https://github.com/DGh0st/DVirtualHome/commit/feacb38268e7b888b7c6867761c48b10e926f925) commit.

**Comment by antalm** [comment]
Thank you, this fix works perfectly.
