### ISSUE TITLE
Add support for iOS 15.7.8

### ISSUE THREAD

**Issue by plia7** [DGh0st/DVirtualHome#9]
Hello @DGh0st

Some say the tweak is crashing in that version. It crashes SpringBoard into Safe Mode
Any chance to fix that for us homeless button people?

Thank you.

**Comment by DGh0st** [comment]
I don't have an iOS 15.7.8 device, so unless you have a crash log there isn't much I can do to fix it.

Not sure what you mean by homeless button but this tweak makes it so you can tap on the home button instead of pressing on it. So it would require a home button (i.e. a non-notched device) to function.

**Comment by plia7** [comment]
> I don't have an iOS 15.7.8 device, so unless you have a crash log there isn't much I can do to fix it.
> 
> 
> 
> Not sure what you mean by homeless button but this tweak makes it so you can tap on the home button instead of pressing on it. So it would require a home button (i.e. a non-notched device) to function.

Yes, that's what I meant by "homeless button", I have the physical home button on my iPhone SE Gen 1 but it's broken, so I had to use dvirtualhome on my ios 12.4 to simulate it with touch id which is working fine.
I want to upgrade my iphone to ios 15.7.8 which has a jailbreak but people say it crashes when trying to use your tweak.

If I upgrade and get you the crash logs, will you be able to see what can be done? Where do you want me to get the crash logs from?

Thank you.

**Comment by DGh0st** [comment]
There is no guarantee that I would be able to fix it as I don't have an iOS 15.7.8 device so I wouldn't recommend risking your jailbreak by updating.

> I want to upgrade my iphone to ios 15.7.8 which has a jailbreak but people say it crashes when trying to use your tweak.

Can you get one of these people to send me a crash log?
Would need to download CrashReporter or Cr4shed and then reproduce issue to get crash logs.

**Comment by plia7** [comment]
> There is no guarantee that I would be able to fix it as I don't have an iOS 15.7.8 device so I wouldn't recommend risking your jailbreak by updating.
> 
> 
> 
> > I want to upgrade my iphone to ios 15.7.8 which has a jailbreak but people say it crashes when trying to use your tweak.
> 
> 
> 
> Can you get one of these people to send me a crash log?
> 
> Would need to download CrashReporter or Cr4shed and then reproduce issue to get crash logs.

too late I did and it works fine but I can’t jailbreak now because my home button is broken and I can’t get into DFU

**Comment by plia7** [comment]
I can confirm it works for rootless jailbreak for this version, so closing ticket.
